version: '3'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      # - ollama:/root/.ollama
      - /mnt/d/docker-volumes/ollama:/root/.ollama  # WSL2 path format

# volumes:
#   ollama:
# volumes section removed since we're using a bind mount and not named volumes