services:
  my-redis:
    image: redis
    container_name: redisCont
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_volume_data:/data
    networks:
      - my-network

volumes:
  redis_volume_data:
networks:
  my-network:
    driver: bridge
