version: "3"
services:
  my-redis:
    image: redis
    container_name: my-redis-container
    ports:
      - 6380:6379
    restart: always
    volumes:
      - redis_volume_data:/data
    networks:
      - my-network

volumes:
  redis_volume_data:
networks:
  my-network:
    driver: bridge
