version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
      - "9009:9009" # Replication interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-config:/etc/clickhouse-server
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    restart: always

  clickhouse-client:
    image: clickhouse/clickhouse-client
    container_name: clickhouse-client
    depends_on:
      - clickhouse-server
    entrypoint: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  clickhouse-data:
  clickhouse-config:
